title: "Мария Данилова, писатель"
description: "Сайт автора"
baseurl: ""          # Use empty string for user/organization pages
url: "https://mdwebsite.github.io"  # Replace with your GitHub Pages URL
markdown: kramdown
